### PR TITLE
Event horizon tutorial

### PR DESCRIPTION
**Pull request by joelhoisko**
## Summary

Update event horizon sample and rework the sample structure a bit

### Changed

- Made the event horizon sample match the incoming [event horizon tutorial](https://github.com/dolittle/Documentation/pull/83) on dolittle.io

### Fixed

- Added the new `"composite": true` to tsconfigs on referenced projects

### CODE REVIEW

**Comment by joelhoisko** [comment]
Could the label be removed so that a new version isn't released? Do we have a "no-release" label?

**Review by woksin — APPROVED** [review]

**Comment by woksin** [comment]
I don't think we should do a patch here?

**Comment by joelhoisko** [comment]
If you don't put a label won't it do a patch release anyway?

**Comment by woksin** [comment]
Nope, but I see that I was to fast with approving this. I'm fixing some config stuff to make it build

**Pull request merged**
